### PR TITLE
 added a class

### PR DESCRIPTION
**Pull request by reaper6947**
i added a class so that its easier to make new objects.

### CODE REVIEW

**Comment by BlakeStevenson** [comment]
Thanks :)

**Comment by reaper6947** [comment]
can u please take a look at what i did in my version ?  i am not sure if its the right way, i added a function that spits only urls.

**Comment by BlakeStevenson** [comment]
> can u please take a look at what i did in my version ? i am not sure if its the right way, i added a function that spits only urls.

Works for me, looks good. Thanks for working on it!

**Comment by BlakeStevenson** [comment]
Also this was really quick and dirty, I wrote it in less than 30 minutes. I may revamp it in the future to not be incredibly inefficient and have the user pass in one array of subreddits, rather than having to create five different variables and concatenate them and stuff.

**Pull request merged**
